### PR TITLE
SPECWWW-795: Add "last updated" note to the prevalence map

### PR DESCRIPTION
**Pull request by yjfnyc**
Jira ticket: [SPECWWW-795](https://simonsfoundation.atlassian.net/browse/SPECWWW-795)

Note: the testing steps below are to illustrate that editing and saving records at the backend or doing operation bulk import data can update field "last_udpate" value with the current date, and the frontend will display the latest date of it.

To test:

- [x] Check out this branch
- [x] Please reference the _README.md_ file in project root directory to make sure your local environment is set up to access 127.0.0.1:8000 successfully. Please make sure to run command `pip install -r requirements.txt` to install all the required packages; make sure to run `python manage.py migrate` to apply schema changes to your local database.
- [x] If you don't have a user to access backend admin yet, please run command `python manage.py createsuperuser` to create one.
- [x] Access backend http://127.0.0.1:8000/submarine/login/ to login
- [x] Access backend page on http://127.0.0.1:8000/submarine/autism_prevalence_map/studies/, and click on button "bulk import", as shown on the screenshot below, to import csv data from our google drive https://drive.google.com/drive/folders/1lHHkm2wATdJh6XxLdd4fDHnL76No1c-J, file name _bulk_import_test.csv_.
Screenshot 2023-02-01 at 4 05 47 PM

- [x] Access the database table "options"(I use a tool called pgAdmin 4), and confirm  there is a row field name "last_updated_on" and value as current date, for example "3 February 2023".
- [x] Access the prevalence map frontend page on http://127.0.0.1:8000/ to confirm you can see the message "Data last updated on ..." on current date on the bottom left of the page similar to the following screenshot.
Screenshot 2023-02-01 at 4 02 06 PM

- [x] Use your database client tool to remove the above mentioned row in table options or change its name value.
- [x] Access the prevalence map frontend page on http://127.0.0.1:8000/ to confirm you can not see the "last updated on ..." message anymore. 
- [x] Access backend admin at http://127.0.0.1:8000/submarine/autism_prevalence_map/studies/, and edit one record and save it.
- [x] Access the prevalence map frontend page on http://127.0.0.1:8000/ to confirm you can see the the message has been changed to the current date.

### CODE REVIEW

**Review by myicicle — CHANGES_REQUESTED** [review]
Can we talk about this? I'm just not understanding the need to store the same date in every row of this table. Would it be possible for you to use context processor instead? It's just one value that applies to the map template, right? So it can just be stored as a context variable: https://docs.djangoproject.com/en/4.1/ref/templates/api/#playing-with-context. Also, could you please double-check if `date.today` is in the Eastern Standard time zone? I think it might be UTC by default.

**Comment by yjfnyc** [comment]
> context processor



> Can we talk about this? I'm just not understanding the need to store the same date in every row of this table. Would it be possible for you to use context processor instead? It's just one value that applies to the map template, right? So it can just be stored as a context variable: https://docs.djangoproject.com/en/4.1/ref/templates/api/#playing-with-context. Also, could you please double-check if `date.today` is in the Eastern Standard time zone? I think it might be UTC by default.

Hi @myicicle, thanks for the suggestion.

 I am not sure how to use context processor to persist the last updated data, can you please be more specific. Seems to me it is a way to pass data to template, and I couldn't find the way to persist data with it.

Adding a field to the database table seems like an overkill for this ticket, and I thought so too initially. Then I realized that it seems like a regular practice for quite a lot of projects I encountered that adding a timestamp field like last modified etc. seems quite common(think Wordpress wp_posts table). So I just went ahead. If there is better way I definitely will use it.

For the time zone issue you raised, I thought I addressed it in tickets before by commenting out line 126 in file settings.py. I will do more testing to make sure it works. Thanks for bring it up.

**Comment by myicicle** [comment]
I also think it's an overkill. I'm wondering if there is another table, like an admin table that stores the admin data, where you can store this last updated date and retrieve it whenever request is made. Do you have another table for this purpose?

As for the time zone, I think you might also have to check with the infrastructure team whether this setting is applied when the time is called from the codes. They might overwrite it as UTC, which has happened to me before at my previous jobs.

**Comment by yjfnyc** [comment]
> I also think it's an overkill. I'm wondering if there is another table, like an admin table that stores the admin data, where you can store this last updated date and retrieve it whenever request is made. Do you have another table for this purpose?
> 
> As for the time zone, I think you might also have to check with the infrastructure team whether this setting is applied when the time is called from the codes. They might overwrite it as UTC, which has happened to me before at my previous jobs.

I explored on admin tables before, but couldn't get the solution. How about consulting @roarmeow . He is way better on research.

Regarding the timezone, I changed the setting, and it works well as far as I can tell. Of course, I won't hurt to consult @rishiraj-rana  regarding your concern.

**Comment by myicicle** [comment]
Sure, you can ask Mike and let me know what he says. For the time zone, yea, it won't hurt to ask the infrastructure team, just in case.

**Comment by yjfnyc** [comment]
> Sure, you can ask Mike and let me know what he says. For the time zone, yea, it won't hurt to ask the infrastructure team, just in case.

I have finished the new implementation according to Mike's suggestion, mainly creating a new table to hold this "last updated on" global information similar to what table wp_options does in Wordpress.

**Review by myicicle — CHANGES_REQUESTED** [review]
I love the new table! One thing is that when I deleted a study, it didn't update the last updated on date.

**Comment by yjfnyc** [comment]
> I love the new table! One thing is that when I deleted a study, it didn't update the last updated on date.

Thanks for the great catch. I have addressed the issue.

**Review by roarmeow — APPROVED** [review]
This looks quite good to me and is certainly more efficient than storing the updated date in each record. I particularly appreciate that it updates the date whether you import data or edit a record. Nicely done! :shipit:

**Pull request merged**
